# Polars

Testing out [Polars](https://pola.rs/).

In [2]:
pip install 'polars[all]'

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: polars[all] in /Users/cmc/Library/Python/3.9/lib/python/site-packages (0.20.3)
Collecting connectorx>=0.3.2
  Downloading connectorx-0.3.2-cp39-cp39-macosx_11_0_arm64.whl (43.7 MB)
     |████████████████████████████████| 43.7 MB 709 kB/s eta 0:00:01
Collecting pydantic
  Downloading pydantic-2.5.3-py3-none-any.whl (381 kB)
     |████████████████████████████████| 381 kB 31.7 MB/s eta 0:00:01
Collecting pandas
  Downloading pandas-2.1.4-cp39-cp39-macosx_11_0_arm64.whl (11.0 MB)
     |████████████████████████████████| 11.0 MB 46.7 MB/s eta 0:00:01
Collecting sqlalchemy
  Downloading SQLAlchemy-2.0.25-cp39-cp39-macosx_11_0_arm64.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 8.0 MB/s eta 0:00:01
Collecting pyiceberg>=0.5.0
  Downloading pyiceberg-0.5.1.tar.gz (418 kB)
     |████████████████████████████████| 418 kB 14.7 MB/s eta 0:00:01
  WARNING: Value for prefixed-purelib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /private/var/folders/7q/fr3mjnb5279fv8k1tz643s140000gn/T/pip-build-env-nk7hp5uy/normal/lib/python3.9/site-packages
  sysconfig: /Library/Python/3.9/site-packages
  WARNING: Value for prefixed-platlib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /private/var/folders/7q/fr3mjnb5279fv8k1tz643s140000gn/T/pip-build-env-nk7hp5uy/normal/lib/python3.9/site-packages
  sysconfig: /Library/Python/3.9/site-packages
  WARNING: Additional context:
  user = False
  home = None
  root = None
  prefix = '/private/var/folders/7q/fr3mjnb5279fv8k1tz643s140000gn/T/pip-build-env-nk7hp5uy/normal'
  WARNING: Value for prefixed-purelib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /private/var/folders/7q/fr3mjnb5279fv8k1tz643s140000gn/T/pip-build-env-nk7hp5uy/overlay/lib/python3.9/site-packages
  sysconfig: /Library/Python/3.9/site-packages
  WARNING: Value for prefixed-platlib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /private/var/folders/7q/fr3mjnb5279fv8k1tz643s140000gn/T/pip-build-env-nk7hp5uy/overlay/lib/python3.9/site-packages
  sysconfig: /Library/Python/3.9/site-packages
  WARNING: Additional context:
  user = False
  home = None
  root = None
  prefix = '/private/var/folders/7q/fr3mjnb5279fv8k1tz643s140000gn/T/pip-build-env-nk7hp5uy/overlay'
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting gevent
  Downloading gevent-23.9.1-cp39-cp39-macosx_11_0_universal2.whl (2.9 MB)
     |████████████████████████████████| 2.9 MB 27.4 MB/s eta 0:00:01
Requirement already satisfied: numpy>=1.16.0 in /Users/cmc/Library/Python/3.9/lib/python/site-packages (from polars[all]) (1.26.3)
Collecting cloudpickle
  Downloading cloudpickle-3.0.0-py3-none-any.whl (20 kB)
Collecting adbc_driver_sqlite
  Downloading adbc_driver_sqlite-0.9.0-py3-none-macosx_11_0_arm64.whl (696 kB)
     |████████████████████████████████| 696 kB 27.0 MB/s eta 0:00:01
Collecting xlsxwriter
  Downloading XlsxWriter-3.1.9-py3-none-any.whl (154 kB)
     |████████████████████████████████| 154 kB 11.5 MB/s eta 0:00:01
Collecting xlsx2csv>=0.8.0
  Downloading xlsx2csv-0.8.2.tar.gz (227 kB)
     |████████████████████████████████| 227 kB 42.7 MB/s eta 0:00:01
  WARNING: Value for prefixed-purelib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /private/var/folders/7q/fr3mjnb5279fv8k1tz643s140000gn/T/pip-build-env-05_qjymb/normal/lib/python3.9/site-packages
  sysconfig: /Library/Python/3.9/site-packages
  WARNING: Value for prefixed-platlib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /private/var/folders/7q/fr3mjnb5279fv8k1tz643s140000gn/T/pip-build-env-05_qjymb/normal/lib/python3.9/site-packages
  sysconfig: /Library/Python/3.9/site-packages
  WARNING: Additional context:
  user = False
  home = None
  root = None
  prefix = '/private/var/folders/7q/fr3mjnb5279fv8k1tz643s140000gn/T/pip-build-env-05_qjymb/normal'
  WARNING: Value for prefixed-purelib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /private/var/folders/7q/fr3mjnb5279fv8k1tz643s140000gn/T/pip-build-env-05_qjymb/overlay/lib/python3.9/site-packages
  sysconfig: /Library/Python/3.9/site-packages
  WARNING: Value for prefixed-platlib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /private/var/folders/7q/fr3mjnb5279fv8k1tz643s140000gn/T/pip-build-env-05_qjymb/overlay/lib/python3.9/site-packages
  sysconfig: /Library/Python/3.9/site-packages
  WARNING: Additional context:
  user = False
  home = None
  root = None
  prefix = '/private/var/folders/7q/fr3mjnb5279fv8k1tz643s140000gn/T/pip-build-env-05_qjymb/overlay'
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  WARNING: Generating metadata for package xlsx2csv produced metadata for project name unknown. Fix your #egg=xlsx2csv fragments.
WARNING: Discarding https://files.pythonhosted.org/packages/c9/d1/70613896bd07a49cfb19312838b8ffb29232e6be5c8e381b953473468e5b/xlsx2csv-0.8.2.tar.gz#sha256=cdd272c82f8b32f1cee76aeaef87b2ee3549661fddf90f7ecf2310967a16fc84 (from https://pypi.org/simple/xlsx2csv/). Requested unknown from https://files.pythonhosted.org/packages/c9/d1/70613896bd07a49cfb19312838b8ffb29232e6be5c8e381b953473468e5b/xlsx2csv-0.8.2.tar.gz#sha256=cdd272c82f8b32f1cee76aeaef87b2ee3549661fddf90f7ecf2310967a16fc84 (from polars[all]) has inconsistent name: filename has 'xlsx2csv', but metadata has 'UNKNOWN'
  Downloading xlsx2csv-0.8.1-py3-none-any.whl (13 kB)
Collecting deltalake>=0.14.0
  Downloading deltalake-0.15.1-cp38-abi3-macosx_11_0_arm64.whl (19.1 MB)
     |████████████████████████████████| 19.1 MB 14.5 MB/s eta 0:00:01
Requirement already satisfied: fsspec in /Users/cmc/Library/Python/3.9/lib/python/site-packages (from polars[all]) (2023.12.2)
Collecting pyarrow>=7.0.0
  Downloading pyarrow-14.0.2-cp39-cp39-macosx_11_0_arm64.whl (24.0 MB)
     |████████████████████████████████| 24.0 MB 1.1 MB/s eta 0:00:011
Collecting hvplot>=0.9.1
  Downloading hvplot-0.9.1-py2.py3-none-any.whl (3.2 MB)
     |████████████████████████████████| 3.2 MB 22.8 MB/s eta 0:00:01     |█████▍                          | 542 kB 22.8 MB/s eta 0:00:01
Collecting pyarrow-hotfix
  Downloading pyarrow_hotfix-0.6-py3-none-any.whl (7.9 kB)
Collecting colorcet>=2
  Downloading colorcet-3.0.1-py2.py3-none-any.whl (1.7 MB)
     |████████████████████████████████| 1.7 MB 34.2 MB/s eta 0:00:01
Collecting param<3.0,>=1.12.0
  Downloading param-2.0.1-py3-none-any.whl (113 kB)
     |████████████████████████████████| 113 kB 44.1 MB/s eta 0:00:01
Requirement already satisfied: packaging in /Users/cmc/Library/Python/3.9/lib/python/site-packages (from hvplot>=0.9.1->polars[all]) (23.1)
Collecting bokeh>=1.0.0
  Downloading bokeh-3.3.3-py3-none-any.whl (6.8 MB)
     |████████████████████████████████| 6.8 MB 11.7 MB/s eta 0:00:01
Collecting holoviews>=1.11.0
  Downloading holoviews-1.18.1-py2.py3-none-any.whl (4.3 MB)
     |████████████████████████████████| 4.3 MB 37.8 MB/s eta 0:00:01
Collecting panel>=0.11.0
  Downloading panel-1.3.6-py2.py3-none-any.whl (20.8 MB)
     |████████████████████████████████| 20.8 MB 14.8 MB/s eta 0:00:01
Requirement already satisfied: Jinja2>=2.9 in /Users/cmc/Library/Python/3.9/lib/python/site-packages (from bokeh>=1.0.0->hvplot>=0.9.1->polars[all]) (3.1.2)
Collecting pillow>=7.1.0
  Downloading pillow-10.2.0-cp39-cp39-macosx_11_0_arm64.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 14.5 MB/s eta 0:00:01
Requirement already satisfied: tornado>=5.1 in /Users/cmc/Library/Python/3.9/lib/python/site-packages (from bokeh>=1.0.0->hvplot>=0.9.1->polars[all]) (6.3.3)
Collecting xyzservices>=2021.09.1
  Downloading xyzservices-2023.10.1-py3-none-any.whl (56 kB)
     |████████████████████████████████| 56 kB 18.1 MB/s eta 0:00:01
Requirement already satisfied: PyYAML>=3.10 in /Users/cmc/Library/Python/3.9/lib/python/site-packages (from bokeh>=1.0.0->hvplot>=0.9.1->polars[all]) (6.0.1)
Collecting contourpy>=1
  Downloading contourpy-1.2.0-cp39-cp39-macosx_11_0_arm64.whl (242 kB)
     |████████████████████████████████| 242 kB 63.1 MB/s eta 0:00:01
Collecting pyct>=0.4.4
  Downloading pyct-0.5.0-py2.py3-none-any.whl (15 kB)
Collecting pyviz-comms>=0.7.4
  Downloading pyviz_comms-3.0.0-py3-none-any.whl (82 kB)
     |████████████████████████████████| 82 kB 3.2 MB/s  eta 0:00:01
Requirement already satisfied: MarkupSafe>=2.0 in /Users/cmc/Library/Python/3.9/lib/python/site-packages (from Jinja2>=2.9->bokeh>=1.0.0->hvplot>=0.9.1->polars[all]) (2.1.3)
Collecting pytz>=2020.1
  Using cached pytz-2023.3.post1-py2.py3-none-any.whl (502 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/cmc/Library/Python/3.9/lib/python/site-packages (from pandas->polars[all]) (2.8.2)
Collecting tzdata>=2022.1
  Downloading tzdata-2023.4-py2.py3-none-any.whl (346 kB)
     |████████████████████████████████| 346 kB 20.1 MB/s eta 0:00:01
Collecting tqdm>=4.48.0
  Using cached tqdm-4.66.1-py3-none-any.whl (78 kB)
Collecting markdown-it-py
  Using cached markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
Requirement already satisfied: bleach in /Users/cmc/Library/Python/3.9/lib/python/site-packages (from panel>=0.11.0->hvplot>=0.9.1->polars[all]) (6.0.0)
Collecting markdown
  Downloading Markdown-3.5.1-py3-none-any.whl (102 kB)
     |████████████████████████████████| 102 kB 26.5 MB/s ta 0:00:01
Collecting linkify-it-py
  Downloading linkify_it_py-2.0.2-py3-none-any.whl (19 kB)
Requirement already satisfied: typing-extensions in /Users/cmc/Library/Python/3.9/lib/python/site-packages (from panel>=0.11.0->hvplot>=0.9.1->polars[all]) (4.8.0)
Requirement already satisfied: requests in /Users/cmc/Library/Python/3.9/lib/python/site-packages (from panel>=0.11.0->hvplot>=0.9.1->polars[all]) (2.31.0)
Collecting mdit-py-plugins
  Downloading mdit_py_plugins-0.4.0-py3-none-any.whl (54 kB)
     |████████████████████████████████| 54 kB 12.4 MB/s eta 0:00:01
Collecting sortedcontainers==2.4.0
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Collecting rich<14.0.0,>=10.11.0
  Downloading rich-13.7.0-py3-none-any.whl (240 kB)
     |████████████████████████████████| 240 kB 52.6 MB/s eta 0:00:01
Collecting click<9.0.0,>=7.1.1
  Downloading click-8.1.7-py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 9.8 MB/s  eta 0:00:01
Collecting strictyaml<2.0.0,>=1.7.0
  Downloading strictyaml-1.7.3-py3-none-any.whl (123 kB)
     |████████████████████████████████| 123 kB 52.8 MB/s eta 0:00:01
Collecting pyparsing<4.0.0,>=3.1.0
  Using cached pyparsing-3.1.1-py3-none-any.whl (103 kB)
Collecting mmhash3<4.0.0,>=3.0.0
  Downloading mmhash3-3.0.1-cp39-cp39-macosx_11_0_arm64.whl (12 kB)
Collecting pydantic-core==2.14.6
  Downloading pydantic_core-2.14.6-cp39-cp39-macosx_11_0_arm64.whl (1.7 MB)
     |████████████████████████████████| 1.7 MB 10.7 MB/s eta 0:00:01
Collecting annotated-types>=0.4.0
  Downloading annotated_types-0.6.0-py3-none-any.whl (12 kB)
Requirement already satisfied: six>=1.5 in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas->polars[all]) (1.15.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/cmc/Library/Python/3.9/lib/python/site-packages (from requests->panel>=0.11.0->hvplot>=0.9.1->polars[all]) (3.2.0)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/cmc/Library/Python/3.9/lib/python/site-packages (from requests->panel>=0.11.0->hvplot>=0.9.1->polars[all]) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /Users/cmc/Library/Python/3.9/lib/python/site-packages (from requests->panel>=0.11.0->hvplot>=0.9.1->polars[all]) (2023.7.22)
Requirement already satisfied: idna<4,>=2.5 in /Users/cmc/Library/Python/3.9/lib/python/site-packages (from requests->panel>=0.11.0->hvplot>=0.9.1->polars[all]) (3.4)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/cmc/Library/Python/3.9/lib/python/site-packages (from rich<14.0.0,>=10.11.0->pyiceberg>=0.5.0->polars[all]) (2.16.1)
Collecting mdurl~=0.1
  Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Collecting adbc-driver-manager
  Downloading adbc_driver_manager-0.9.0-cp39-cp39-macosx_11_0_arm64.whl (261 kB)
     |████████████████████████████████| 261 kB 3.5 MB/s eta 0:00:01
Requirement already satisfied: webencodings in /Users/cmc/Library/Python/3.9/lib/python/site-packages (from bleach->panel>=0.11.0->hvplot>=0.9.1->polars[all]) (0.5.1)
Collecting zope.event
  Downloading zope.event-5.0-py3-none-any.whl (6.8 kB)
Collecting zope.interface
  Downloading zope.interface-6.1-cp39-cp39-macosx_11_0_arm64.whl (202 kB)
     |████████████████████████████████| 202 kB 18.6 MB/s eta 0:00:01
Collecting greenlet>=2.0.0
  Downloading greenlet-3.0.3-cp39-cp39-macosx_11_0_universal2.whl (269 kB)
     |████████████████████████████████| 269 kB 5.4 MB/s eta 0:00:01
Collecting uc-micro-py
  Downloading uc_micro_py-1.0.2-py3-none-any.whl (6.2 kB)
Requirement already satisfied: importlib-metadata>=4.4 in /Users/cmc/Library/Python/3.9/lib/python/site-packages (from markdown->panel>=0.11.0->hvplot>=0.9.1->polars[all]) (6.8.0)
Requirement already satisfied: zipp>=0.5 in /Users/cmc/Library/Python/3.9/lib/python/site-packages (from importlib-metadata>=4.4->markdown->panel>=0.11.0->hvplot>=0.9.1->polars[all]) (3.17.0)
Requirement already satisfied: setuptools in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from zope.event->gevent->polars[all]) (58.0.4)
Building wheels for collected packages: pyiceberg
  Building wheel for pyiceberg (PEP 517) ... done
  Created wheel for pyiceberg: filename=pyiceberg-0.5.1-cp39-cp39-macosx_14_0_arm64.whl size=527582 sha256=460f2fb33d28df351dd1f65841874e740e9e5f1d4953f861d877ec4b0e94911c
  Stored in directory: /Users/cmc/Library/Caches/pip/wheels/fb/8c/3f/f25c02bddafeae467122e8757c9275c5981cf708f1d182f494
Successfully built pyiceberg
Installing collected packages: tzdata, pytz, mdurl, xyzservices, uc-micro-py, pillow, param, pandas, markdown-it-py, contourpy, tqdm, pyviz-comms, pyct, mdit-py-plugins, markdown, linkify-it-py, bokeh, pydantic-core, panel, colorcet, annotated-types, zope.interface, zope.event, strictyaml, sortedcontainers, rich, pyparsing, pydantic, pyarrow-hotfix, pyarrow, mmhash3, holoviews, greenlet, click, adbc-driver-manager, xlsxwriter, xlsx2csv, sqlalchemy, pyiceberg, hvplot, gevent, deltalake, connectorx, cloudpickle, adbc-driver-sqlite
Successfully installed adbc-driver-manager-0.9.0 adbc-driver-sqlite-0.9.0 annotated-types-0.6.0 bokeh-3.3.3 click-8.1.7 cloudpickle-3.0.0 colorcet-3.0.1 connectorx-0.3.2 contourpy-1.2.0 deltalake-0.15.1 gevent-23.9.1 greenlet-3.0.3 holoviews-1.18.1 hvplot-0.9.1 linkify-it-py-2.0.2 markdown-3.5.1 markdown-it-py-3.0.0 mdit-py-plugins-0.4.0 mdurl-0.1.2 mmhash3-3.0.1 pandas-2.1.4 panel-1.3.6 param-2.0.1 pillow-10.2.0 pyarrow-14.0.2 pyarrow-hotfix-0.6 pyct-0.5.0 pydantic-2.5.3 pydantic-core-2.14.6 pyiceberg-0.5.1 pyparsing-3.1.1 pytz-2023.3.post1 pyviz-comms-3.0.0 rich-13.7.0 sortedcontainers-2.4.0 sqlalchemy-2.0.25 strictyaml-1.7.3 tqdm-4.66.1 tzdata-2023.4 uc-micro-py-1.0.2 xlsx2csv-0.8.1 xlsxwriter-3.1.9 xyzservices-2023.10.1 zope.event-5.0 zope.interface-6.1
WARNING: You are using pip version 21.2.4; however, version 23.3.2 is available.
You should consider upgrading via the '/Applications/Xcode.app/Contents/Developer/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [3]:
import polars as pl
from datetime import datetime

In [4]:
df = pl.DataFrame(
    {
        "integer": [1, 2, 3],
        "date": [
            datetime(2022, 1, 1),
            datetime(2022, 1, 2),
            datetime(2022, 1, 3),
        ],
        "float": [4.0, 5.0, 6.0],
    }
)

print(df)

shape: (3, 3)
┌─────────┬─────────────────────┬───────┐
│ integer ┆ date                ┆ float │
│ ---     ┆ ---                 ┆ ---   │
│ i64     ┆ datetime[μs]        ┆ f64   │
╞═════════╪═════════════════════╪═══════╡
│ 1       ┆ 2022-01-01 00:00:00 ┆ 4.0   │
│ 2       ┆ 2022-01-02 00:00:00 ┆ 5.0   │
│ 3       ┆ 2022-01-03 00:00:00 ┆ 6.0   │
└─────────┴─────────────────────┴───────┘

In [8]:
df = pl.read_csv("../data_files/video_game_sales.csv", ignore_errors=True)
print(df)

shape: (16_598, 11)
┌───────┬─────────────────┬──────────┬──────┬───┬──────────┬──────────┬─────────────┬──────────────┐
│ Rank  ┆ Name            ┆ Platform ┆ Year ┆ … ┆ EU_Sales ┆ JP_Sales ┆ Other_Sales ┆ Global_Sales │
│ ---   ┆ ---             ┆ ---      ┆ ---  ┆   ┆ ---      ┆ ---      ┆ ---         ┆ ---          │
│ i64   ┆ str             ┆ str      ┆ i64  ┆   ┆ f64      ┆ f64      ┆ f64         ┆ f64          │
╞═══════╪═════════════════╪══════════╪══════╪═══╪══════════╪══════════╪═════════════╪══════════════╡
│ 1     ┆ Wii Sports      ┆ Wii      ┆ 2006 ┆ … ┆ 29.02    ┆ 3.77     ┆ 8.46        ┆ 82.74        │
│ 2     ┆ Super Mario     ┆ NES      ┆ 1985 ┆ … ┆ 3.58     ┆ 6.81     ┆ 0.77        ┆ 40.24        │
│       ┆ Bros.           ┆          ┆      ┆   ┆          ┆          ┆             ┆              │
│ 3     ┆ Mario Kart Wii  ┆ Wii      ┆ 2008 ┆ … ┆ 12.88    ┆ 3.79     ┆ 3.31        ┆ 35.82        │
│ 4     ┆ Wii Sports      ┆ Wii      ┆ 2009 ┆ … ┆ 11.01    ┆ 3.28     ┆ 2.96        ┆ 33.0         │
│       ┆ Resort          ┆          ┆      ┆   ┆          ┆          ┆             ┆              │
│ …     ┆ …               ┆ …        ┆ …    ┆ … ┆ …        ┆ …        ┆ …           ┆ …            │
│ 16597 ┆ Men in Black    ┆ GC       ┆ 2003 ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0         ┆ 0.01         │
│       ┆ II: Alien       ┆          ┆      ┆   ┆          ┆          ┆             ┆              │
│       ┆ Escape          ┆          ┆      ┆   ┆          ┆          ┆             ┆              │
│ 16598 ┆ SCORE           ┆ PS2      ┆ 2008 ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0         ┆ 0.01         │
│       ┆ International   ┆          ┆      ┆   ┆          ┆          ┆             ┆              │
│       ┆ Baja 1000: T…   ┆          ┆      ┆   ┆          ┆          ┆             ┆              │
│ 16599 ┆ Know How 2      ┆ DS       ┆ 2010 ┆ … ┆ 0.01     ┆ 0.0      ┆ 0.0         ┆ 0.01         │
│ 16600 ┆ Spirits &       ┆ GBA      ┆ 2003 ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0         ┆ 0.01         │
│       ┆ Spells          ┆          ┆      ┆   ┆          ┆          ┆             ┆              │
└───────┴─────────────────┴──────────┴──────┴───┴──────────┴──────────┴─────────────┴──────────────┘

In [12]:
df.group_by("Year").count()

shape: (40, 2)
┌──────┬───────┐
│ Year ┆ count │
│ ---  ┆ ---   │
│ i64  ┆ u32   │
╞══════╪═══════╡
│ 1982 ┆ 36    │
│ 1999 ┆ 338   │
│ 2014 ┆ 582   │
│ 1993 ┆ 60    │
│ …    ┆ …     │
│ 2015 ┆ 614   │
│ 2010 ┆ 1259  │
│ 1984 ┆ 14    │
│ 1995 ┆ 219   │
└──────┴───────┘

In [18]:
df.select(pl.col("Year").sort().head(2), pl.col("Genre").filter(pl.col("Year") == 1).sum())

shape: (2, 2)
┌──────┬───────┐
│ Year ┆ Genre │
│ ---  ┆ ---   │
│ i64  ┆ str   │
╞══════╪═══════╡
│ null ┆ null  │
│ null ┆ null  │
└──────┴───────┘